Using custom data configuration default-06084af75ccc14fc
Reusing dataset json (/home/lily/hh638/.cache/huggingface/datasets/json/default-06084af75ccc14fc/0.0.0/ac0ca5f5289a6cf108e706efcf040422dbbfa8e658dee6a819f20d76bb84d26b)
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00, 16.07it/s]
Traceback (most recent call last):
  File "gpt.py", line 15, in <module>
    response = openai.ChatCompletion.create(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/openai/api_requestor.py", line 216, in request
    result = self.request_raw(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/openai/api_requestor.py", line 516, in request_raw
    result = _thread_context.session.request(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/lily/hh638/anaconda3/envs/simplification/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
